[profile.dev]
strip = true
opt-level = 1

[profile.release]
strip = true
lto = true
opt-level = "z"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["mcriddle", "mcriddle-daemon", "questioneer"]
