[package]
name = "questioneer"
version.workspace = true
edition.workspace = true

[dependencies]
indexmap = "2.6.0"
mcriddle = { path = "../mcriddle" }
ratatui = "0.29.0"
tokio = { version = "1.41.1", features = ["full"] }
