[package]
name = "questioneer"
version.workspace = true
edition.workspace = true

[dependencies]
hex = "0.4.3"
indexmap = "2.6.0"
mcriddle = { path = "../mcriddle" }
ratatui = "0.29.0"
tokio = { version = "1.41.1", features = ["full"] }
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
