[package]
name = "chatomato"
version.workspace = true
edition.workspace = true

[dependencies]
mcriddle = { version = "0.1.0", path = "../mcriddle" }
ratatui = "0.29.0"
rusqlite = "0.32.1"
tokio = { version = "1.41.1", features = ["full"] }
